spring:
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://qhdduswh.ipdisk.co.kr:3306/qhddusl?serverTimezone=Asia/Seoul
    username: qhddusl
    password: qhddusl2004
  security:
    user:
      name: vermouth
      password: vermouth
      roles: manager