spring:
  datasource:
    url: /
    username: /
    password: /
  security:
    user:
      name: vermouth
      password: vermouth
      roles: manager
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: 12345678901234567890123456789012
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.admin.vermouth.domain
server:
  servlet:
    session:
      timeout: 10m