spring:
  datasource:
    url: jdbc:mysql://qhdduswh.ipdisk.co.kr:3306/qhddusl?serverTimezone=Asia/Seoul
    username: qhddusl
    password: qhddusl2004
  security:
    user:
      name: vermouth
      password: vermouth
      roles: manager
  jpa:
    show-sql: true
jwt:
  secret: 12345678901234567890123456789012
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.admin.vermouth.domain
server:
  servlet:
    session:
      timeout: 10m